---
- hosts: nodes
  become: yes

  tasks:
  - name: create the directory Test for testing files
    file:
      dest: /etc/folder
      mode: 0654
      state: directory

  - name: create the directory Lali for yaml files
    file:
      dest: /etc/doc
      mode: 0655
      state: directory    

      
     
